### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by tunikakeks** [Luuuuuis/PrivateServer#1]
How to compile it to a .jar on Linux and how to Install CloudNet 2.0?

**Comment by sudo2222** [comment]
> How to compile it to a .jar on Linux and how to Install CloudNet 2.0?
> 

You just need to Install maven on Linux. Compile it with maven and then put the output jar into your bungeecord plugins folder.

**Comment by tunikakeks** [comment]
And how to compile it with maven? @leginhee

**Comment by sudo2222** [comment]
Create a nee folder, then Put the src folder in there. In the new folder use the command "sudo mvn clean package" to compile it. Then you should see a new folder named target. You have to put the hat file in the target directory in your bungeecord plugins folder. (The one without dependencies) @tunikakeks

**Comment by tunikakeks** [comment]
Okay but now I get an error when I use /Privateserver

```[11:44:15 INFO]: [KeksDev] disconnected with: NoClassDefFoundError : de/dytanic/cloudnet/api/CloudAPI @ de.luuuuuis.privateserver.commands.PrivateServerCmd:27```

**Comment by tunikakeks** [comment]
@leginhee

**Comment by sudo2222** [comment]
Did you changed the config.yml? @tunikakeks

**Comment by tunikakeks** [comment]
@leginhee I have only a config.json and idk what to change

**Comment by sudo2222** [comment]
@tuikakeks

{
  "prefix": "Â§6PREFIX Â§8Â» Â§7",   -> Prefix
  "messages": {
    "startingServer": "Starting server of gamemode %s...",  |
    "noGroupSpecified": "Â§cNo gamemode specified!",    |  -> Messages
    "startingTitle": "Â§6Starting server%s"                           |
  },
  "template": "default",  -> nothing to change
  "groups": [ "Lobby", "test" ],  -> Lobby group
  "maxServersRunning": 20,  -> Max Servers running at the same time
  "maxServersPerUser": 1,  -> Max online Servers per user
  "memory": 320  -> Memory per Server
}

**Comment by tunikakeks** [comment]
This doesn't fix the error

**Comment by sudo2222** [comment]
I'm not the creator of the plugin. But you could try the file I already compiled. Everything works perfect for me.
http://www.mediafire.com/file/c84mi01zhpwldw1/PrivateServer-1.0-SNAPSHOT.jar/file
@tunikakeks

**Comment by tunikakeks** [comment]
Okay I will Test it

**Comment by tunikakeks** [comment]
Also @leginhee:

• The Plugin doesn't load
• Did you use CloudNet? 
• If yes, can I use CloudNet for PocketMine-MP Servers too?

**Comment by sudo2222** [comment]
You need cloudnet for this plugin. I use Cloudnet v2. I don't know much about bedrock edition server, but do they use Bungeecord to connect server? The plugin could be for java servers only. As much I know CloudNet can be used for Bedrock Servers too.

**Comment by tunikakeks** [comment]
There is a BungeeCord Fork named 'Waterdog' for Bedrock Servers.

**Comment by sudo2222** [comment]
I don't think the plugin works for Bedrock Servers

**Comment by Luuuuuis** [comment]
> I don't think the plugin works for Bedrock Servers

I don't think so, but you may try (It's possible that it uses the same API).
If you are still interested you can use my compiled version. :) https://github.com/Luuuuuis/PrivateServer/releases
